# Generated by Django 4.0.3 on 2022-03-28 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('passid', models.IntegerField(max_length=14)),
                ('email', models.EmailField(max_length=120)),
                ('nationality', models.CharField(max_length=30)),
                ('mobile', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField(auto_created=True, max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('cost', models.IntegerField(max_length=1000)),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='hotelapp.guest')),
            ],
        ),
    ]
