# Generated by Django 4.0.3 on 2022-03-28 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_alter_guest_passid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='guest_id',
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(max_length=100)),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_reserve', to='hotelapp.guest')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_reserved', to='hotelapp.room')),
            ],
        ),
    ]
