# Generated by Django 4.0.3 on 2022-03-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0003_remove_room_guest_id_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.IntegerField(max_length=100),
        ),
    ]
