# Generated by Django 4.0.3 on 2022-03-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0004_alter_room_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
